version: '3.8'

services:
  frontend-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    ports:
      - "3002:3001"
    volumes:
      - ..:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
      - NODE_ENV=test
      - PORT=3001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    command: sh -c "npm install && npm test"  # Ensure dependencies are installed before tests
    networks:
      - test-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  test-network:
    name: duties-test-network