version: '3.8'

services:
  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: duties
    ports:
      - "5433:5432"  # Different port to avoid conflicts with dev database
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  test-runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    environment:
      DB_HOST: test-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: duties
      NODE_ENV: test
    depends_on:
      - test-db
    command: npm run test:coverage
    volumes:
      - ../coverage:/app/coverage
      - ../src:/app/src
      - ../tests:/app/tests 